<?php if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_book-details',
		'title' => 'Book Details',
		'fields' => array (
			array (
				'key' => 'field_5612718c24ad2',
				'label' => 'Author',
				'name' => 'book_author',
				'type' => 'text',
				'instructions' => 'Enter the Author name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_561271e324ad3',
				'label' => 'Publisher',
				'name' => 'book_publisher',
				'type' => 'text',
				'instructions' => 'Enter publisher name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5612720424ad4',
				'label' => 'Year of Publish',
				'name' => 'book_year',
				'type' => 'date_picker',
				'instructions' => 'Enter the Year of publish',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5612723b24ad5',
				'label' => 'ISBN',
				'name' => 'book_isbn',
				'type' => 'text',
				'instructions' => 'Enter the ISBN number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5612724a24ad6',
				'label' => 'Pages',
				'name' => 'book_pages',
				'type' => 'text',
				'instructions' => 'Enter the page number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5612726c24ad7',
				'label' => 'Language',
				'name' => 'book_language',
				'type' => 'text',
				'instructions' => 'Enter the language of book',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'download',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}